a = true;
if a {
    print("Yes")
}
---
a=$((1))
if [ "$a" == 1 ]; then
"echo" "-ne" "Yes"
fi
+++
Yes
===
a = 3;
if a > 2 {
    print("Yes")
} else if (a == 2) {
    print("No")
}
---
a=$((3))
if [ $(($a > 2)) == 1 ]; then
"echo" "-ne" "Yes"
else
if [ "$a" == $((2)) ]; then
"echo" "-ne" "No"
fi
fi
+++
Yes
===
a = 3;
if a > 2 {
    print("Yes")
} else if (a == 2) {
    print("Maybe")
} else {
    print("No")
}
---
a=$((3))
if [ $(($a > 2)) == 1 ]; then
"echo" "-ne" "Yes"
else
if [ "$a" == $((2)) ]; then
"echo" "-ne" "Maybe"
else
"echo" "-ne" "No"
fi
fi
+++
Yes
===
func foo() {
    return true
}
a = true;
if a == foo() {
    print("Yes")
}
---
function foo {
"echo" "-ne" $((1))
return
}
a=$((1))
if [ "$a" == $("foo") ]; then
"echo" "-ne" "Yes"
fi
+++
Yes
===
func foo() {
    return 10
}
a = 9
if a < (foo() + foo()) {
    print("Yes")
}
---
function foo {
"echo" "-ne" $((10))
return
}
a=$((9))
if [ $(($a < $(($("foo") + $("foo"))))) == 1 ]; then
"echo" "-ne" "Yes"
fi
+++
Yes
