n = 0
i = 0
j = 1
while n < 60 {
    k = i + j
    i = j
    j = k
    n = n + 1
}
print(k)
---
n=$((0))
i=$((0))
j=$((1))
while [ $(($n < 60)) == 1 ]; do
k=$(($i+$j))
i="$j"
j="$k"
n=$(($n+1))
done

"echo" "-ne" "$k"
+++
2504730781961
===
list = array(1, 2, 3)
for i in list {
    print(i)
}
---
list=($((1)) $((2)) $((3)))
for i in "${list[@]}"; do
"echo" "-ne" "$i"
done
+++
123
===
list = array("one", 2, "3.3")
for i in list {
    print(i)
}
---
list=("one" $((2)) "3.3")
for i in "${list[@]}"; do
"echo" "-ne" "$i"
done
+++
one23.3
===
n = 0
while n < (100 - 40) {
    n = n + 1
}
print(n)
---
n=$((0))
while [ $(($n < $((100 - 40)))) == 1 ]; do
n=$(($n+1))
done

"echo" "-ne" "$n"
+++
60
===
func foo() {
    return 60
}
n = 0
while n < foo() {
    n = n + 1
}
print(n)
---
function foo {
"echo" "-ne" $((60))
return
}
n=$((0))
while [ $(($n < $("foo"))) == 1 ]; do
n=$(($n+1))
done

"echo" "-ne" "$n"
+++
60
===
func foo() {
    return 60
}
n = 0
while n < (foo() + foo()) {
    n = n + 1
}
print(n)
---
function foo {
"echo" "-ne" $((60))
return
}
n=$((0))
while [ $(($n < $(($("foo") + $("foo"))))) == 1 ]; do
n=$(($n+1))
done

"echo" "-ne" "$n"
+++
120
