n = 0
i = 0
j = 1
while n < 60 {
    k = i + j
    i = j
    j = k
    n = n + 1
}
print(k)
---
n=$((0))
i=$((0))
j=$((1))
while [ $(($n < 60)) == 1 ]; do
k=$(($i+$j))
i="$j"
j="$k"
n=$(($n+1))
done

"echo" "-ne" "$k"
+++
2504730781961
===
list = array(1, 2, 3)
for i in list {
    print(i)
}
---
list=($((1)) $((2)) $((3)))
for i in "${list[@]}"; do
"echo" "-ne" "$i"
done
+++
123
===
list = array("one", 2, "3.3")
for i in list {
    print(i)
}
---
list=("one" $((2)) "3.3")
for i in "${list[@]}"; do
"echo" "-ne" "$i"
done
+++
one23.3
