import("./modules/arrays")
func foo(arr) {
    a = unpack(arr)
    return arrays.length(pack(a))
}
a = array("zero", 1, "2", "three", 4, "5")
print(foo(pack(a)))
---
function arrays_length {
local arrays_a
local arrays_arr
arrays_arr="$1"
arrays_a=($@)
"echo" "-ne" ${#arrays_a[@]}
return
}

function foo {
local a
local arr
arr="$1"
a=($@)
"echo" "-ne" $("arrays_length" ${a[@]})
return
}
a=("zero" $((1)) "2" "three" $((4)) "5")
"echo" "-ne" $("foo" ${a[@]})
+++
6
