import("./fixtures/modules/foo")
baz = "bar"
func get() {
    return baz
}
print(get())
print(foo.get())
print(foo.sub.get())
---
foo_baz="bar"
function foo_get {
"echo" "-ne" "$foo_baz"
return
}
foo_sub_baz="bar"
function foo_sub_get {
"echo" "-ne" "$foo_sub_baz"
return
}
baz="bar"
function get {
"echo" "-ne" "$baz"
return
}
"echo" "-ne" $("get")
"echo" "-ne" $("foo_get")
"echo" "-ne" $("foo_sub_get")
+++
barbarbar
