import("./modules/os")
e = os.exists("file.txt")
print(e)
---
function os_exists {
[ -e $1 ]
ex=$((!$?))
"echo" "-ne" "$ex"
return
}

e=$("os_exists" "file.txt")
"echo" "-ne" "$e"
+++
0
===
import("./modules/os")
e = os.exists("./modules/os/main.bs")
print(e)
---
function os_exists {
[ -e $1 ]
ex=$((!$?))
"echo" "-ne" "$ex"
return
}

e=$("os_exists" "./modules/os/main.bs")
"echo" "-ne" "$e"
+++
1
