func foo () {
    return 1
}
---
function foo {
"echo" "-ne" $((1))
return
}
===
func foo (a b) {
    return 1
}
---
function foo {
local a
a="$1"
local b
b="$2"
"echo" "-ne" $((1))
return
}
===
v1 = "Global V1"
v2 = "Global V2"
func foo(p) {
    v1 = "Local " + p
    v2 = "V3 Modified."
}
foo("Var")
---
v1="Global V1"
v2="Global V2"
function foo {
local v1
local v2
local p
p="$1"
v1="Local ""$p"
v2="V3 Modified."
}
"foo" "Var"
