a = true;
if a {
    print("Yes")
}
---
a=$((1))
if [ "$a" == 1 ]; then
"echo" "-ne" "Yes"
fi
+++
Yes
===
a = 3;
if a > 2 {
    print("Yes")
} else if (a == 2) {
    print("No")
}
---
a=$((3))
if [ $(($a > 2)) == 1 ]; then
"echo" "-ne" "Yes"
else
if [ "$a" == $((2)) ]; then
"echo" "-ne" "No"
fi
fi
+++
Yes
===
a = 3;
if a > 2 {
    print("Yes")
} else if (a == 2) {
    print("Maybe")
} else {
    print("No")
}
---
a=$((3))
if [ $(($a > 2)) == 1 ]; then
"echo" "-ne" "Yes"
else
if [ "$a" == $((2)) ]; then
"echo" "-ne" "Maybe"
else
"echo" "-ne" "No"
fi
fi
+++
Yes
