func fibonacci(num) {
    if (num == 0) {
        return 0
    } else if (num == 1) {
        return 1
    } else {
        return fibonacci(num - 2) + fibonacci(num - 1)
    }
}
println(fibonacci(8))
---
function fibonacci {
local num
num="$1"
if [ "$num" == $((0)) ]; then
"echo" "-ne" $((0))
return
else
if [ "$num" == $((1)) ]; then
"echo" "-ne" $((1))
return
else
"echo" "-ne" $(($("fibonacci" $(($num - 2))) + $("fibonacci" $(($num - 1)))))
return
fi
fi
}
"echo" "-e" $("fibonacci" $((8)))
